"""Showcase sheet brand data (Task 20). One dense 1080x1620 infographic per brand."""

SHOWCASE = {
    "portfolio": {
        "bg": "#0B1220",
        "accent": "#38BDF8",
        "header_logo": "ABHILASH // VERSE",
        "header_tagline": "Web Developer and AI Engineer",
        "hero_line": "I turn ideas into real world and problems into solutions",
        "hero_subtitle": "I build fast, beautiful, and intelligent digital experiences that help businesses grow.",
        "hero_location": "Delhi, India",
        "cta_primary": "Explore my work",
        "cta_secondary": "View journey",
        "qualities": [
            ("FAST", "Optimized for speed and performance"),
            ("RESPONSIVE", "Looks perfect on all devices"),
            ("SEO OPTIMIZED", "Clean structure, schema"),
            ("ACCESSIBLE", "WCAG friendly"),
            ("CLEAN CODE", "Maintainable, scalable"),
        ],
        "tech": ["Astro", "TypeScript", "Tailwind CSS", "Three.js", "Motion One", "JavaScript", "HTML5", "CSS3"],
        "features": [
            "Immersive 3D experience",
            "Smooth animations",
            "Fully responsive",
            "SEO optimized",
            "Lightning fast",
            "Accessible",
        ],
        "optimization": [
            "3D scene loads after window load",
            "Display image optimized (-41.4%)",
            "Critical JS reduced to ~7.8KB",
            "Three.js (551KB) loaded on idle",
            "Unused CSS removed",
            "Web fonts avoided",
        ],
        "projects_title": "Featured projects",
        "projects": [
            ("GymOS", "LIVE", "Full-stack SaaS for Indian gyms"),
            ("Web Scraper Studio", "LIVE", "Full-stack B2B lead generation"),
            ("ReferencePilot", "IN PROGRESS", "AI tool"),
            ("Nagra Tech Computers", "LIVE", "Website"),
            ("AlgoWithAbhi", "IN PROGRESS", "AI + Trading"),
        ],
        "services_title": "Services and pricing",
        "services": [
            ("Frontend Website", "Rs 1,500"),
            ("Full-Stack Website", "Rs 3,500"),
            ("Portfolio Website", "Rs 2,100"),
            ("SaaS", "Rs 5,500"),
            ("Automation", "Rs 4,500"),
            ("Custom System", "Custom Quote"),
        ],
        "guarantees": ["Honest Pricing", "On-Time Delivery", "Clean Code", "Support and Maintenance"],
        "scores_title": "Lighthouse scores",
        "scores": [
            ("100", "Perf"),
            ("100", "A11y"),
            ("100", "BP"),
            ("100", "SEO"),
            ("100", "PWA"),
        ],
        "deployed": "Vercel",
        "connect": ["LinkedIn", "GitHub", "Instagram", "Telegram", "Email"],
        "footer_tagline": "BUILDING DIGITAL EXPERIENCES THAT MAKE AN IMPACT.",
        "footer_hashtags": "#WebDeveloper #AIEngineer #Portfolio #OpenToWork",
    },
    "gymos": {
        "bg": "#1F4E78",
        "accent": "#22C55E",
        "header_logo": "GYMOS",
        "header_tagline": "Multi-Tenant SaaS for Indian Gyms",
        "hero_line": "Keep members paying. Keep members coming back.",
        "hero_subtitle": "Member retention, fee tracking, and attendance in one dashboard for Indian gyms of 150-500 members.",
        "hero_location": "Pune / Delhi / Indore",
        "cta_primary": "Try live demo",
        "cta_secondary": "Book walkthrough",
        "qualities": [
            ("RETENTION FIRST", "Spot at-risk members in 14 days"),
            ("PAYMENT TRACKING", "Due lists + collection status"),
            ("QR ATTENDANCE", "Check-in in seconds"),
            ("RENEWAL FORECAST", "30 and 60 day cash flow"),
            ("WIN-BACK PLAYBOOK", "Call scripts + conversion tracking"),
        ],
        "tech": ["Next.js", "TypeScript", "FastAPI", "Postgres", "Tailwind CSS", "Supabase", "Playwright", "Vercel"],
        "features": [
            "Multi-tenant isolation",
            "Owner + staff roles",
            "QR check-in kiosk",
            "Due-list dashboard",
            "Absent-member reports",
            "Renewal calendar",
        ],
        "optimization": [
            "Sub-2s LCP on 4G",
            "Server components for 5K+ rows",
            "Preview deploys per PR",
            "Zero-downtime migrations",
            "Point-in-time backups",
            "RLS row-level security",
        ],
        "projects_title": "Featured modules",
        "projects": [
            ("Member management", "CORE", "Profiles, plans, renewals"),
            ("Fee tracking", "CORE", "Dues, receipts, defaulters"),
            ("Attendance logging", "CORE", "QR kiosk + history"),
            ("Retention reports", "PRO", "At-risk + churn signals"),
            ("Renewal forecast", "PRO", "30/60-day cash view"),
            ("Win-back tracker", "PRO", "Calls + conversions"),
        ],
        "services_title": "Plans by gym size",
        "services": [
            ("150-250 members", "Starter"),
            ("251-350 members", "Growth"),
            ("351-500 members", "Pro"),
            ("500+ members", "Enterprise"),
            ("Onboarding", "2-hour setup"),
            ("Migration", "Free Excel import"),
        ],
        "guarantees": ["2-hour onboarding", "Excel import", "Free migration", "WhatsApp support"],
        "scores_title": "Results",
        "scores": [
            ("38%", "Retention"),
            ("48K", "Recovered"),
            ("25%", "Month-4"),
        ],
        "deployed": "Vercel + Supabase",
        "connect": ["WhatsApp +91 99531 49058", "bodycare-gym.vercel.app", "Email"],
        "footer_tagline": "BUILT FOR INDIAN GYMS. PROVEN IN PUNE.",
        "footer_hashtags": "#GymOS #SaaS #FitnessTech #Retention",
    },
    "webscraper": {
        "bg": "#1F4E78",
        "accent": "#22C55E",
        "header_logo": "WEB SCRAPER STUDIO",
        "header_tagline": "B2B Leads and Data Extraction",
        "hero_line": "500 to 5,000 verified B2B leads in 24-48 hours",
        "hero_subtitle": "Fresh Google Maps extraction for Indian sales teams: phone, email, address, ratings, ready for your CRM.",
        "hero_location": "Serving all India",
        "cta_primary": "Get free sample",
        "cta_secondary": "See pricing",
        "qualities": [
            ("FRESH DATA", "Live Google Maps extraction"),
            ("VERIFIED PHONES", "98% phone coverage"),
            ("DEDUPLICATED", "Under 5% duplicates"),
            ("EMAIL ENRICHED", "30-55% hit rate from websites"),
            ("DELIVERED FAST", "24-48 hour turnaround"),
        ],
        "tech": ["Python", "Playwright", "Crawl4AI", "FastAPI", "Pydantic AI", "Streamlit", "Gemini 3.5", "Vercel"],
        "features": [
            "Multi-city bulk",
            "Multi-query orchestrator",
            "Email enrichment",
            "Phone normalization",
            "GST verification (coming)",
            "DND scrub (coming)",
        ],
        "optimization": [
            "Automated dedupe",
            "Phone format +91 10-digit",
            "Address whitespace cleanup",
            "Category classification",
            "Email SMTP validation",
            "Human QA on 100 rows",
        ],
        "projects_title": "Sample deliveries",
        "projects": [
            ("2,300 Mumbai dental clinics", "36H", "98% phones"),
            ("5,000 Bengaluru agents", "48H", "97% phones"),
            ("35 Delhi gym leads", "7 MIN", "55% emails"),
        ],
        "services_title": "Packages",
        "services": [
            ("Starter 500 leads", "Rs 5,000"),
            ("Growth 1,000 + email", "Rs 10,000"),
            ("Scale 5,000 multi-city", "Rs 25,000"),
            ("Enterprise 10,000+", "Custom Quote"),
            ("Free sample", "10 rows free"),
            ("Delivery", "XLSX + CSV + JSON"),
        ],
        "guarantees": ["Free 10-row sample", "No advance for first sample", "24-48h delivery", "XLSX + CSV + JSON"],
        "scores_title": "Track record",
        "scores": [
            ("77", "Q4 demo"),
            ("4", "Industries"),
            ("500+", "Cities"),
            ("55%", "Email max"),
        ],
        "deployed": "Vercel landing + Local pipeline",
        "connect": ["WhatsApp +91 99531 49058", "webscraperstudio.vercel.app", "Email"],
        "footer_tagline": "VERIFIED B2B LEADS. DELIVERED IN 24-48 HOURS.",
        "footer_hashtags": "#B2BLeads #LeadGen #SalesTech #Data",
    },
}

SHOWCASE_WIDTH = 1080
SHOWCASE_HEIGHT = 1620
